vim.g.mapleader = " "
vim.keymap.set("n","<leader>pv", vim.cmd.Ex)
vim.keymap.set("n","<leader>o", "o <Esc>")
vim.keymap.set("n","<leader>P", "o<Esc>p")
vim.keymap.set("n","<leader>j", "i<Enter><Esc>")
vim.keymap.set("v","J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v","K", ":m '<-2<CR>gv=gv")
vim.keymap.set("n","<C-d>", "<C-d>zz")
vim.keymap.set("n","<C-u>", "<C-u>zz")
vim.keymap.set("n","n", "nzzzv")
vim.keymap.set("n","N", "Nzzzv")
vim.keymap.set("x","<leader>p","\"_dP")
vim.keymap.set("n", "<leader>s", [[:%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>]])
vim.keymap.set("n","<C-h>", "<C-w>h")
vim.keymap.set("n","<C-j>", "<C-w>j")
vim.keymap.set("n","<C-k>", "<C-w>k")
vim.keymap.set("n","<C-l>", "<C-w>l")
vim.keymap.set("n","<leader>sh", ":sp<CR><C-w>j")
vim.keymap.set("n","<leader>sv", ":vsp<CR><C-w>l")
vim.keymap.set("n","<leader>h", ":sp<CR><C-w>j:term<CR>A")
vim.keymap.set("n","<leader>v", ":vsp<CR><C-w>l:term<CR>A")
vim.keymap.set("n","<leader>q",":q<CR>")
vim.keymap.set("n","<leader>Q",":q!<CR>")
vim.keymap.set("n","<A-S-Right>","<C-w>>")
vim.keymap.set("n","<A-S-Left>","<C-w><")
vim.keymap.set("n","<A-S-Up>","<C-w>+")
vim.keymap.set("n","<A-S-Down>","<C-w>-")
vim.keymap.set("n","<C-a>", "ggVG")
